PACKAGE_NAME="rtw89"
PACKAGE_VERSION="7.3davenport"
BUILD_EXCLUSIVE_KERNEL="^(6\.[6-9]\.|6\.1[0-9]\.|7\.)"
AUTOINSTALL=yes
MAKE="KVER=${kernelver} 'make' modules"
CLEAN="true"

BUILT_MODULE_NAMES=(
"rtw89_8851b_git"
"rtw89_8851bu_git"
"rtw89_8852a_git"
"rtw89_8852au_git"
"rtw89_8852b_git"
"rtw89_8852b_common_git"
"rtw89_8852bu_git"
"rtw89_8852c_git"
"rtw89_8852cu_git"
"rtw89_8922a_git"
"rtw89_8922au_git"
"rtw89_core_git"
"rtw89_usb_git"
)

if [ -e "/lib/modules/${kernelver}/build/.config" ] && grep -q "CONFIG_PCI=y" "/lib/modules/${kernelver}/build/.config"; then
BUILT_MODULE_NAMES+=(
"rtw89_8851be_git"
"rtw89_8852ae_git"
"rtw89_8852be_git"
"rtw89_8852bt_git"
"rtw89_8852bte_git"
"rtw89_8852ce_git"
"rtw89_8922ae_git"
"rtw89_8922d_git"
"rtw89_8922de_git"
"rtw89_pci_git"
)
fi

for i in "${!BUILT_MODULE_NAMES[@]}"; do
BUILT_MODULE_NAME[i]="${BUILT_MODULE_NAMES[i]}"
DEST_MODULE_LOCATION[i]="/updates/dkms/rtw89"
done
